import { sql, relations } from 'drizzle-orm';
import { sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import type { z } from 'zod';

// ---- Users Table ----
export const users = sqliteTable('users', {
  id: text('id').primaryKey(), // UUID generated by application
  email: text('email').unique().notNull(),
  password: text('password').notNull(),
  name: text('name').notNull(),
  timezone: text('timezone').notNull().default('Asia/Taipei'),
  membershipLevel: text('membership_level', { enum: ['anonymous', 'member', 'vip'] }).notNull().default('anonymous'),
  preferences: text('preferences', { mode: 'json' }).$type<{
    language: string;
    displayMode: string;
    notifications: boolean;
    theme: 'light' | 'dark';
  } | null>(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

// ---- Chart Records Table ----
export const chartRecords = sqliteTable('chart_records', {
	id: text('id').primaryKey(), // UUID generated by application
	userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }), // Foreign key to users
	type: text('type', { enum: ['bazi', 'purple-star', 'integrated'] }).notNull(),
	chartData: text('chart_data', { mode: 'json' }).notNull(),
	metadata: text('metadata', { mode: 'json' }).$type<{
		name?: string;
		birthDate: string;
		birthTime: string;
		location: string;
	}>().notNull(),
	createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

// ---- Analysis Records Table ----
export const analysisRecords = sqliteTable('analysis_records', {
	id: text('id').primaryKey(), // UUID generated by application
	userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }), // Foreign key to users
	chartId: text('chart_id').references(() => chartRecords.id, { onDelete: 'cascade' }), // Foreign key to chart_records
	analysisType: text('analysis_type').notNull(),
	result: text('result', { mode: 'json' }).notNull(),
	createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});


// ---- RELATIONS ----
export const usersRelations = relations(users, ({ many }) => ({
	charts: many(chartRecords),
	analyses: many(analysisRecords),
}));

export const chartRecordsRelations = relations(chartRecords, ({ one, many }) => ({
	user: one(users, {
		fields: [chartRecords.userId],
		references: [users.id],
	}),
	analyses: many(analysisRecords),
}));

export const analysisRecordsRelations = relations(analysisRecords, ({ one }) => ({
	user: one(users, {
		fields: [analysisRecords.userId],
		references: [users.id],
	}),
	chart: one(chartRecords, {
		fields: [analysisRecords.chartId],
		references: [chartRecords.id],
	}),
}));


// ---- Zod Schemas for validation ----
export const insertUserSchema = createInsertSchema(users);
export const selectUserSchema = createSelectSchema(users);
export type User = z.infer<typeof selectUserSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;

export const insertChartRecordSchema = createInsertSchema(chartRecords);
export const selectChartRecordSchema = createSelectSchema(chartRecords);
export type ChartRecord = z.infer<typeof selectChartRecordSchema>;
export type InsertChartRecord = z.infer<typeof insertChartRecordSchema>;

export const insertAnalysisRecordSchema = createInsertSchema(analysisRecords);
export const selectAnalysisRecordSchema = createSelectSchema(analysisRecords);
export type AnalysisRecord = z.infer<typeof selectAnalysisRecordSchema>;
export type InsertAnalysisRecord = z.infer<typeof insertAnalysisRecordSchema>;
