import { sql, relations } from 'drizzle-orm';
import { sqliteTable, text, uniqueIndex, index, integer } from 'drizzle-orm/sqlite-core';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import type { z } from 'zod';

// ---- Users Table ----
export const users = sqliteTable('users', {
  id: text('id').primaryKey(), // UUID generated by application
  email: text('email').unique().notNull(),
  password: text('password').notNull(),
  name: text('name').notNull(),
  timezone: text('timezone').notNull().default('Asia/Taipei'),
  membershipLevel: text('membership_level', { enum: ['anonymous', 'member', 'vip'] }).notNull().default('anonymous'),
  preferences: text('preferences', { mode: 'json' }).$type<{
    language: string;
    displayMode: string;
    notifications: boolean;
    theme: 'light' | 'dark';
  } | null>(),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

// ---- Chart Records Table ----
export const chartRecords = sqliteTable('chart_records', {
	id: text('id').primaryKey(), // UUID generated by application
	userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }), // Foreign key to users
	type: text('type', { enum: ['bazi', 'purple-star', 'integrated'] }).notNull(),
	chartData: text('chart_data', { mode: 'json' }).notNull(),
	metadata: text('metadata', { mode: 'json' }).$type<{
		name?: string;
		birthDate: string;
		birthTime: string;
		location: string;
	}>().notNull(),
	createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});

// ---- Analysis Records Table ----
export const analysisRecords = sqliteTable('analysis_records', {
	id: text('id').primaryKey(), // UUID generated by application
	userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }), // Foreign key to users
	chartId: text('chart_id').references(() => chartRecords.id, { onDelete: 'cascade' }), // Foreign key to chart_records
	analysisType: text('analysis_type').notNull(),
	result: text('result', { mode: 'json' }).notNull(),
	createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
});


// ---- Advanced Analysis Records Table ----
export const advancedAnalysisRecords = sqliteTable('advanced_analysis_records', {
	id: text('id').primaryKey(), // UUID generated by application
	chartId: text('chart_id').notNull().references(() => chartRecords.id, { onDelete: 'cascade' }), // Foreign key to chart_records
	analysisType: text('analysis_type').notNull().default('ai-advanced-zh-TW'),
	result: text('result', { mode: 'json' }).notNull(),
	createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
}, (table) => ({
	chartIdTypeIdx: index('idx_advanced_analysis_chart_id_type').on(table.chartId, table.analysisType),
	createdAtIdx: index('idx_advanced_analysis_created_at').on(table.createdAt),
}));

// ---- RELATIONS ----
export const usersRelations = relations(users, ({ many }) => ({
	charts: many(chartRecords),
	analyses: many(analysisRecords),
}));

export const chartRecordsRelations = relations(chartRecords, ({ one, many }) => ({
	user: one(users, {
		fields: [chartRecords.userId],
		references: [users.id],
	}),
	analyses: many(analysisRecords),
}));

export const analysisRecordsRelations = relations(analysisRecords, ({ one }) => ({
	user: one(users, {
		fields: [analysisRecords.userId],
		references: [users.id],
	}),
	chart: one(chartRecords, {
		fields: [analysisRecords.chartId],
		references: [chartRecords.id],
	}),
}));

export const advancedAnalysisRecordsRelations = relations(advancedAnalysisRecords, ({ one }) => ({
	chart: one(chartRecords, {
		fields: [advancedAnalysisRecords.chartId],
		references: [chartRecords.id],
	}),
}));

// ---- Daily Question Analytics Tables ----
export const dailyQuestionLogs = sqliteTable('daily_question_logs', {
	id: text('id').primaryKey(), // UUID
	chartId: text('chart_id').notNull(),
	question: text('question').notNull(),
	finalAnswer: text('final_answer'),
	isSuccess: integer('is_success', { mode: 'boolean' }).default(true),
	
	// 模型與備援資訊
	provider: text('provider').notNull().default('gemini'), // 'gemini' | 'azure'
	model: text('model'),
	isFallback: integer('is_fallback', { mode: 'boolean' }).default(false),
	fallbackReason: text('fallback_reason'),

	// 性能指標
	totalLatencyMs: integer('total_latency_ms'),
	promptTokens: integer('prompt_tokens'),
	completionTokens: integer('completion_tokens'),
	totalTokens: integer('total_tokens'),

	createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(strftime('%s', 'now'))`),
}, (table) => ({
	chartIdIdx: index('dql_chart_id_idx').on(table.chartId),
	createdAtIdx: index('dql_created_at_idx').on(table.createdAt),
}));

// Agent 執行歷程表
export const agentExecutionTraces = sqliteTable('agent_execution_traces', {
	id: text('id').primaryKey(), // UUID
	logId: text('log_id').notNull().references(() => dailyQuestionLogs.id),
	stepNumber: integer('step_number').notNull(),
	
	thought: text('thought'),
	action: text('action'),
	actionInput: text('action_input'),
	observation: text('observation'),
	
	stepLatencyMs: integer('step_latency_ms'),
	
	createdAt: integer('created_at', { mode: 'timestamp' }).default(sql`(strftime('%s', 'now'))`),
}, (table) => ({
	logIdIdx: index('aet_log_id_idx').on(table.logId),
}));

export const dailyQuestionLogsRelations = relations(dailyQuestionLogs, ({ many }) => ({
	traces: many(agentExecutionTraces),
}));

export const agentExecutionTracesRelations = relations(agentExecutionTraces, ({ one }) => ({
	log: one(dailyQuestionLogs, {
		fields: [agentExecutionTraces.logId],
		references: [dailyQuestionLogs.id],
	}),
}));


// ---- Zod Schemas for validation ----
export const insertUserSchema = createInsertSchema(users);
export const selectUserSchema = createSelectSchema(users);
export type User = z.infer<typeof selectUserSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;

export const insertChartRecordSchema = createInsertSchema(chartRecords);
export const selectChartRecordSchema = createSelectSchema(chartRecords);
export type ChartRecord = z.infer<typeof selectChartRecordSchema>;
export type InsertChartRecord = z.infer<typeof insertChartRecordSchema>;

export const insertAnalysisRecordSchema = createInsertSchema(analysisRecords);
export const selectAnalysisRecordSchema = createSelectSchema(analysisRecords);
export type AnalysisRecord = z.infer<typeof selectAnalysisRecordSchema>;

export const insertAdvancedAnalysisRecordSchema = createInsertSchema(advancedAnalysisRecords);
export const selectAdvancedAnalysisRecordSchema = createSelectSchema(advancedAnalysisRecords);
export type AdvancedAnalysisRecord = z.infer<typeof selectAdvancedAnalysisRecordSchema>;
export type InsertAdvancedAnalysisRecord = z.infer<typeof insertAdvancedAnalysisRecordSchema>;
export type InsertAnalysisRecord = z.infer<typeof insertAnalysisRecordSchema>;
